require("colors");
s = require("./rtsp.js");
console.log(a = s.client_setup().green);
console.log(s.server_setup(a).cyan);
console.log(a = s.client_play().green);
console.log(s.server_play().cyan);
console.log(a = s.client_pause().green);
console.log(s.server_pause().cyan);
console.log(a = s.client_teardown().green);
console.log(s.server_teardown().cyan);